# This is a basic workflow to help you get started with Actions

name: CI with value

# Controls when the workflow will run
on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
    inputs:
      value1:
        type: string
        description: value1
      value2:
        type: string
        description: value2
        
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v6

      # Runs a single command using the runners shell
      - name: Run a one-line script
        run: echo Hello, world!

      - name: log value 1
        run: echo "value1 ${{ github.event.inputs.value1 }}"

      - name: log value 2
        run: echo "value2 ${{ github.event.inputs.value2 }}"

      - name: create summary header
        run: echo "## Values' >> $GITHUB_STEP_SUMMARY
      
      - name: create summary values
        run: echo "value1 ${{ github.event.inputs.value1 }}, value2 ${{ github.event.inputs.value2 }}"
        
      - name: sleep 10 seconds
        run: sleep 10

      - name: sleep 30 seconds
        run: sleep 30

      - name: sleep another 30 seconds
        run: sleep 30

      # Runs a set of commands using the runners shell
      - name: Run a multi-line script
        run: |
          echo Add other actions to build,
          echo test, and deploy your project.
